"""
Build a static dashboard data snapshot.

Run from the repository root:
    python radar_dashboard/build_static.py

The generated static/data.js lets static/index.html work directly from the
filesystem without starting radar_dashboard/app.py.
"""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

try:
    from app import load_papers, summarize
except ModuleNotFoundError:
    from radar_dashboard.app import load_papers, summarize


STATIC_DIR = Path(__file__).resolve().parent / "static"
OUTPUT_PATH = STATIC_DIR / "data.js"


def main():
    papers = load_papers()
    payload = {
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "summary": summarize(papers),
        "papers": papers,
    }

    body = (
        "// Auto-generated by radar_dashboard/build_static.py.\n"
        "// Do not edit by hand; rerun the script after data changes.\n"
        "window.RADAR_STATIC_DATA = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUTPUT_PATH.write_text(body, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH} ({len(papers)} papers)")


if __name__ == "__main__":
    main()
